# Generated by Django 4.1.3 on 2022-12-11 15:20

import creditcards.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_expiry', creditcards.models.CardExpiryField(verbose_name='expiration_date')),
                ('cc_number', creditcards.models.CardNumberField(max_length=25, verbose_name='card_number')),
                ('cc_code', creditcards.models.SecurityCodeField(max_length=4, verbose_name='security_code')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_card', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
