# Generated by Django 4.1.3 on 2022-12-07 13:11

import creditcards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_expiry', creditcards.models.CardExpiryField(verbose_name='expiration_date')),
                ('cc_number', creditcards.models.CardNumberField(max_length=25, verbose_name='card_number')),
                ('cc_code', creditcards.models.SecurityCodeField(max_length=4, verbose_name='security_code')),
            ],
        ),
    ]
