# Generated by Django 4.1.3 on 2022-12-07 19:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reg', '0005_alter_user_photo'),
        ('card', '0002_payment_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='Card',
        ),
    ]
