# Generated by Django 4.1.3 on 2022-12-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
