# Generated by Django 4.1.3 on 2022-12-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0003_user_birthday_user_photo_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='media/avatar.jpeg', null=True, upload_to=''),
        ),
    ]
