# Generated by Django 4.1.3 on 2022-12-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0004_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='media/avatar.jpeg', upload_to=''),
        ),
    ]
