# Generated by Django 4.1.3 on 2022-12-07 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_rename_payment_card'),
        ('reg', '0005_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_card', to='card.card'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
