# Generated by Django 4.1.3 on 2022-12-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0007_addresses_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='flat',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='floor',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='home',
            field=models.PositiveIntegerField(),
        ),
    ]
