# Generated by Django 4.1.3 on 2022-12-08 09:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0003_alter_food_category_alter_food_fit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=155)),
                ('home', models.IntegerField()),
                ('flat', models.IntegerField()),
                ('floor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('number', models.IntegerField()),
                ('note', models.CharField(max_length=100)),
                ('adress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cart.adresses')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('amount', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(20), django.core.validators.MinLengthValidator(0)])),
                ('image', models.ImageField(upload_to='')),
                ('price', models.PositiveIntegerField()),
                ('allergy', models.TextField(max_length=255)),
                ('cutlery', models.BooleanField(default=False)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.food')),
            ],
        ),
    ]
