# Generated by Django 4.1.3 on 2022-12-14 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('snack', 'snack'), ('dinner', 'dinner')], max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('kcal', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'monday'), (1, 'tuesday'), (2, 'wednesday'), (3, 'thursday'), (4, 'friday'), (5, 'saturday'), (6, 'sunday')], null=True)),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=255)),
                ('calories', models.PositiveSmallIntegerField()),
                ('carbohydrates', models.PositiveSmallIntegerField()),
                ('squirrels', models.FloatField()),
                ('fats', models.FloatField()),
                ('ingredients', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.category')),
                ('fit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.fit')),
            ],
        ),
    ]
