# Generated by Django 4.1.3 on 2022-12-04 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('kcal', models.PositiveSmallIntegerField()),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('snackdinner', 'snackdinner')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='day',
            field=models.CharField(choices=[('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday'), ('sunday', 'sunday')], max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Week',
        ),
        migrations.AddField(
            model_name='food',
            name='fit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='menu.fit'),
        ),
    ]
