# Generated by Django 4.1.3 on 2022-12-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='breakfast',
            field=models.IntegerField(choices=[], null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='dinner',
            field=models.IntegerField(choices=[], null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='lunch',
            field=models.IntegerField(choices=[], null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='snack',
            field=models.IntegerField(choices=[], null=True),
        ),
    ]
