# Generated by Django 4.1.3 on 2022-12-04 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_fit_food_category_alter_food_day_delete_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('snack', 'snack'), ('dinner', 'dinner')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='fit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='food', to='menu.fit'),
        ),
    ]
