# Generated by Django 4.1.3 on 2022-12-09 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_set_breakfast_set_dinner_set_lunch_set_snack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='set',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='set',
            name='lunch',
        ),
        migrations.RemoveField(
            model_name='set',
            name='snack',
        ),
        migrations.AddField(
            model_name='set',
            name='foods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='menu.food'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('snack', 'snack'), ('dinner', 'dinner')], max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.category'),
        ),
    ]
