# Generated by Django 4.1.3 on 2022-12-09 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='fit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='set', to='menu.fit'),
        ),
    ]
