# Generated by Django 4.1.3 on 2022-12-09 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_set_foods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='foods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='menu.food'),
        ),
    ]
