# Generated by Django 4.1.3 on 2022-12-09 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='fit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.fit'),
        ),
    ]
