# Generated by Django 4.1.3 on 2022-12-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_set_fit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='foods',
        ),
        migrations.AddField(
            model_name='set',
            name='breakfast',
            field=models.IntegerField(choices=[(1, 'test'), (2, 'test2'), (3, 'reotrrtr')], null=True),
        ),
    ]
