# Generated by Django 4.1.3 on 2022-12-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_remove_set_foods_set_breakfast'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='dinner',
            field=models.IntegerField(choices=[(1, 'test'), (2, 'test2'), (3, 'reotrrtr')], null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='lunch',
            field=models.IntegerField(choices=[(1, 'test'), (2, 'test2'), (3, 'reotrrtr')], null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='snack',
            field=models.IntegerField(choices=[(1, 'test'), (2, 'test2'), (3, 'reotrrtr')], null=True),
        ),
    ]
