# Generated by Django 4.1.3 on 2022-12-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_set_dinner_set_lunch_set_snack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='set',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='set',
            name='lunch',
        ),
        migrations.RemoveField(
            model_name='set',
            name='snack',
        ),
        migrations.AddField(
            model_name='set',
            name='category',
            field=models.ManyToManyField(to='menu.category'),
        ),
    ]
