# Generated by Django 4.1.3 on 2022-12-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_remove_set_breakfast_remove_set_dinner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='food',
            field=models.ManyToManyField(to='menu.food'),
        ),
    ]
