# Generated by Django 4.1.3 on 2022-12-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_set_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='category',
        ),
        migrations.RemoveField(
            model_name='set',
            name='food',
        ),
        migrations.AddField(
            model_name='set',
            name='breakfast',
            field=models.IntegerField(choices=[(1, 'test'), (2, 'test2'), (3, 'reotrrtr')], null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='dinner',
            field=models.IntegerField(choices=[(1, 'test'), (2, 'test2'), (3, 'reotrrtr')], null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='lunch',
            field=models.IntegerField(choices=[(1, 'test'), (2, 'test2'), (3, 'reotrrtr')], null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='snack',
            field=models.IntegerField(choices=[(1, 'test'), (2, 'test2'), (3, 'reotrrtr')], null=True),
        ),
    ]
